

# BrieFlow cluster configuration file

default-resources:
    slurm_partition: 20
    slurm_account: wibrusers
    mem_mb: 2000
    tasks: 1
    cpus_per_task: 3
    runtime: 400
    slurm_extra: "'--output=slurm/slurm_output/rule/%j.out'"
jobs: 100

set-resources:
   # preprocessing
    extract_metadata_sbs:
        mem_mb: 500
    combine_metadata_sbs:
        mem_mb: 2000
    extract_metadata_phenotype:
        mem_mb: 500
    combine_metadata_phenotype:
        mem_mb: 2000
    convert_sbs:
        mem_mb: 500
    convert_ph:
        mem_mb: 500
    calculate_ic_sbs:
        mem_mb: 50000
    calculate_ic_phenotype:
        mem_mb: 400000

    # sbs
    align_sbs:
        mem_mb: 2000
    log_filter:
        mem_mb: 2000
    compute_standard_deviation:
        mem_mb: 2000
    find_peaks:
        mem_mb: 500
    max_filter:
        mem_mb: 1500
    apply_ic_field_sbs:
        mem_mb: 2000
    segment_sbs:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3000
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    extract_bases:
        mem_mb: 750
    call_reads:
        mem_mb: 1000
    call_cells:
        mem_mb: 1000
    extract_sbs_info:
        mem_mb: 500
    combine_reads:
        mem_mb: 20000
    combine_cells:
        mem_mb: 20000
    combine_sbs_info:
        mem_mb: 20000
    eval_segmentation_sbs:
        mem_mb: 50000
    eval_mapping:
        mem_mb: 50000
        cpus_per_task: 12
    segment_sbs_paramsearch:
        mem_mb: 3000
        cpus_per_task: 4
    summarize_segment_sbs_paramsearch:
        mem_mb: 2000

    # phenotype
    apply_ic_field_phenotype:
        mem_mb: 2000
    align_phenotype:
        mem_mb: 2000
    segment_phenotype:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3000
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    identify_cytoplasm:
        mem_mb: 1000
    extract_phenotype_info:
        mem_mb: 1000
    merge_phenotype_info:
        mem_mb: 20000
    extract_phenotype_cp:
        mem_mb: 2000
    merge_phenotype_cp:
        mem_mb: 300000
    eval_segmentation_phenotype:
        mem_mb: 2000
    eval_features:
        mem_mb: 2000
    segment_phenotype_paramsearch:
        mem_mb: 3000
        cpus_per_task: 4
    summarize_segment_phenotype_paramsearch:
        mem_mb: 2000

    # merge
    fast_alignment:
        mem_mb: 10000
        cpus_per_task: 4
    merge:
        mem_mb: 10000
        cpus_per_task: 4
    format_merge:
        mem_mb: 10000
    eval_merge:
        mem_mb: 10000
    clean_merge:
        mem_mb: 10000
    deduplicate_merge:
        mem_mb: 10000
        cpus_per_task: 4
    final_merge:
        mem_mb: 500000

    # aggregate
    clean_transform_standardize:
        mem_mb: 500000
    split_phases:
        mem_mb: 500000
    process_mitotic_gene_data:
        mem_mb: 100000
    process_interphase_gene_data:
        mem_mb: 500000
    process_all_gene_data:
        mem_mb: 500000
    prepare_mitotic_montage_data:
        mem_mb: 800000
    prepare_interphase_montage_data:
        mem_mb: 800000
    generate_mitotic_montage:
        mem_mb: 2000
    generate_interphase_montage:
        mem_mb: 2000
    eval_aggregate:
        mem_mb: 500000

    # cluster
    generate_dataset:
        mem_mb: 2000
    phate_leiden_clustering:
        mem_mb: 10000
    benchmark_clusters:
        mem_mb: 10000
    cluster_eval:
        mem_mb: 10000
